checks:
  python:
    code_rating: true
    duplicate_code: true
build:
  environment:
    python: 3.9.17
  dependencies:
    override:
     - pip install .[dev]
  tests:
    override:
     - py-scrutinizer-run
