[tool.poetry]
name = "annif-test-pypi"
version = "0.59.0-dev"
description = "Automated subject indexing and classification tool"
authors = ["Osma Suominen <osma.suominen@helsinki.fi>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://annif.org"
repository = "https://github.com/NatLibFi/Annif"
documentation = "https://github.com/NatLibFi/Annif/wiki"
keywords = [
    "machine-learning",
    "text-classification",
    "rest-api",
    "code4lib",
    "subject-indexing"
]

classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]

packages = [
    {include = "annif"}
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"

connexion = {version = "2.14.*", extras = ["swagger-ui"]}
swagger_ui_bundle = "*"
flask = ">=1.0.4,<3"
flask-cors = "*"
click = "8.0.*"
click-log = "*"
joblib = "1.1.0"
nltk = "*"
gensim = "4.2.*"
scikit-learn = "1.1.1"
scipy = "1.8.*"
rdflib = ">=4.2,<7.0"
gunicorn = "*"
numpy = "1.23.*"
optuna = "2.10.*"
stwfsapy = "0.3.*"
python-dateutil = "*"
tomli = "2.0.*"
simplemma = "0.7.*"

fasttext = {version = "0.9.2", optional = true}
voikko = {version = "*", optional = true}
tensorflow-cpu = {version = "2.9.1", optional = true}
lmdb = {version = "1.3.0", optional = true}
omikuji = {version = "0.5.*", optional = true}
yake = {version = "0.4.5", optional = true}
pycld3 = {version = "*", optional = true}
spacy = {version = "3.3.*", optional = true}

[tool.poetry.dev-dependencies]
py = "*"
pytest = "*"
requests = "*"
codecov = "*"
coverage = "<=6.2"
pytest-cov = "*"
pytest-watch = "*"
pytest-flask = "*"
pytest-flake8 = "*"
flake8 = "<5"
bumpversion = "*"
autopep8 = "*"

[tool.poetry.extras]
fasttext = ["fasttext"]
voikko = ["voikko"]
nn = ["tensorflow-cpu", "lmdb"]
omikuji = ["omikuji"]
yake = ["yake"]
pycld3 = ["pycld3"]
spacy = ["spacy"]

[tool.poetry.scripts]
annif = "annif.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--flake8"
