name: CI/CD
on:
  push:
    branches:
    - test-pypi-release
    tags:
    - '*'
  pull_request:
  workflow_dispatch:
jobs:
  publish-release:
    name: publish release
    # needs: test
    runs-on: ubuntu-20.04
    # if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      uses: snok/install-poetry@2bf112a0f6979928eb6b011f39700db589c5961e  # v1.3.1
    - name: Set up Python 3.9
      uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5  # v4.2.0
      with:
        python-version: '3.9'
        cache: 'poetry'
        cache-dependency-path: 'pyproject.toml'
    - name: Build and publish distribution to PyPI
      env:
        POETRY_REPOSITORIES_TESTPYPI_URL: https://test.pypi.org/legacy/
        POETRY_HTTP_BASIC_TESTPYPI_USERNAME: __token__
        POETRY_HTTP_BASIC_TESTPYPI_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        poetry publish --build -r testpypi
